// Package ghproxy implements a reverse proxy for the GitHub API that enforces
// repository-level scoping on the user's GitHub token. The proxy runs inside
// the dcx process, listens on HTTPS with a self-signed certificate, and
// forwards allowed requests to api.github.com after rewriting the Host header
// and injecting the host's GitHub token. Requests targeting repositories other
// than the configured one are rejected with 403 Forbidden.
package ghproxy

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"io"
	"log/slog"
	"math/big"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/kobus-v-schoor/dcx/internal/config"
)

// ProxyHost is the hostname used in the TLS certificate's Subject Alternative
// Name. The proxy generates a self-signed certificate with this hostname so
// the gh CLI can verify the TLS connection. In practice, GH_HOST is set to
// the Docker gateway IP (detected at runtime) plus the proxy port, so the
// certificate also includes an IP SAN for the gateway. The hostname SAN
// provides a fallback for environments where host.docker.internal is
// routable.
const ProxyHost = "host.docker.internal"

// DefaultCACertPath is the default container path where the CA certificate is
// copied so the gh CLI trusts the proxy's self-signed TLS certificate. Can be
// overridden via Options.CACertPath. Defined as a constant here for
// convenience; the canonical source is config.DefaultGHCLICACertPath.
const DefaultCACertPath = config.DefaultGHCLICACertPath

// DefaultAPIURL is the default GitHub API URL that the proxy forwards requests
// to. Can be overridden via Options.APIURL for GitHub Enterprise Server.
// Defined as a constant here for convenience; the canonical source is
// config.DefaultGHCLIAPIURL.
const DefaultAPIURL = config.DefaultGHCLIAPIURL

// DefaultCertExpiry is the default validity duration for the self-signed TLS
// certificates generated by the proxy. The certificates are ephemeral — they
// only need to last for the duration of a dcx exec session. Can be overridden
// via Options.CertExpiry. Defined as a constant here for convenience; the
// canonical source is config.DefaultGHCLICertExpiry.
const DefaultCertExpiry = config.DefaultGHCLICertExpiry

// Options holds the configuration for creating and starting a GitHub API
// proxy. All fields have sensible defaults — zero values fall back to those
// defaults. Construct via DefaultOptions for a starting point with defaults
// pre-filled.
type Options struct {
	// Token is the user's GitHub token read from the host (via gh auth token
	// or the GITHUB_TOKEN/GH_TOKEN env var). It is never written to disk or
	// logged. The proxy injects it as the Authorization header on forwarded
	// requests, replacing whatever the container-side gh CLI sends.
	Token string

	// Repository is the allowed repository in "owner/repo" format. Requests
	// targeting a different repository are rejected with 403 Forbidden. If
	// empty, all repository-scoped requests are allowed (no scoping enforced).
	Repository string

	// GatewayIP is the host's IP address on the Docker bridge network. The
	// container uses this IP to reach the proxy. It is included in the TLS
	// certificate's IP SANs so the gh CLI can verify the connection.
	GatewayIP string

	// BindAddr is the address the proxy listens on. Defaults to GatewayIP
	// (more secure — only reachable from the container's network) if empty.
	// Set to "0.0.0.0" to listen on all interfaces (needed in some Docker
	// network setups).
	BindAddr string

	// APIURL is the GitHub API URL to forward requests to. Defaults to
	// "https://api.github.com" if empty. Override for GitHub Enterprise
	// Server (e.g. "https://github.example.com/api/v3").
	APIURL string

	// CACertPath is the container path where the CA certificate is copied.
	// Defaults to "/opt/dcx/gh-proxy/ca.crt" if empty. The CA cert is
	// referenced by both NODE_EXTRA_CA_CERTS (for Node.js-based tools) and
	// the combined CA bundle referenced by SSL_CERT_FILE (for Go-based
	// programs).
	CACertPath string

	// CertExpiry is the duration for which the generated TLS certificates
	// (both CA and server) are valid. Defaults to 24 hours if zero. The
	// certificates are ephemeral — they only need to last for the duration
	// of a dcx exec session.
	CertExpiry time.Duration

	// AllowedPaths is a list of non-repository API path prefixes that are
	// allowed through the proxy even when they don't match the configured
	// repository. If empty, all non-repo paths are allowed (default behaviour).
	// When non-empty, only paths that start with one of the listed prefixes
	// are allowed through in addition to repo-scoped paths. For example,
	// ["/user", "/graphql"] allows /user and /graphql but blocks /orgs/...
	AllowedPaths []string
}

// caCertPath returns the effective CA cert container path, using the default
// if the option is empty.
func (o Options) caCertPath() string {
	if o.CACertPath != "" {
		return o.CACertPath
	}
	return DefaultCACertPath
}

// caBundlePath returns the container path for the combined CA bundle (system
// certs + proxy CA cert). This is derived from the CA cert path by replacing
// the extension with "-bundle.crt". The combined bundle is used for
// SSL_CERT_FILE so that Go programs trust both the system CAs and the proxy's
// self-signed CA. The proxy CA cert alone is used for NODE_EXTRA_CA_CERTS,
// which appends to the system trust store rather than replacing it.
func (o Options) caBundlePath() string {
	base := o.caCertPath()
	// Replace .crt extension with -bundle.crt
	if strings.HasSuffix(base, ".crt") {
		return base[:len(base)-4] + "-bundle.crt"
	}
	return base + "-bundle"
}

// apiURL returns the effective GitHub API URL, using the default if the
// option is empty.
func (o Options) apiURL() string {
	if o.APIURL != "" {
		return o.APIURL
	}
	return DefaultAPIURL
}

// certExpiry returns the effective certificate expiry duration, using the
// default if the option is zero.
func (o Options) certExpiry() time.Duration {
	if o.CertExpiry > 0 {
		return o.CertExpiry
	}
	return DefaultCertExpiry
}

// bindAddr returns the effective bind address, using GatewayIP if the option
// is empty. Binding to the gateway IP only (rather than 0.0.0.0) is more
// secure as it limits the proxy's attack surface to the Docker bridge network.
func (o Options) bindAddr() string {
	if o.BindAddr != "" {
		return o.BindAddr
	}
	return o.GatewayIP
}

// CACertPathResolved returns the effective CA cert container path, using the
// default if the option is empty.
func (o Options) CACertPathResolved() string {
	return o.caCertPath()
}

// CABundlePathResolved returns the container path for the combined CA bundle
// (system certs + proxy CA cert). The combined bundle is used for
// SSL_CERT_FILE so that Go programs trust both the system CAs and the proxy's
// self-signed CA.
func (o Options) CABundlePathResolved() string {
	return o.caBundlePath()
}

// APIURLResolved returns the effective GitHub API URL, using the default if
// the option is empty.
func (o Options) APIURLResolved() string {
	return o.apiURL()
}

// CertExpiryResolved returns the effective certificate expiry duration, using
// the default if the option is zero.
func (o Options) CertExpiryResolved() time.Duration {
	return o.certExpiry()
}

// BindAddrResolved returns the effective bind address, using GatewayIP if the
// option is empty.
func (o Options) BindAddrResolved() string {
	return o.bindAddr()
}

// Proxy handles HTTP/HTTPS requests from the gh CLI inside the devcontainer,
// enforces repository-level scoping, and forwards allowed requests to the
// configured GitHub API URL. It runs as an HTTPS server with a self-signed
// certificate generated on startup.
type Proxy struct {
	// opts holds the proxy configuration including token, repository, and
	// network settings.
	opts Options

	// listener is the TCP listener the proxy server uses. Bound to the
	// configured address on a random available port so the proxy is reachable
	// from the Docker container.
	listener net.Listener

	// server is the HTTPS server that serves the proxy. It uses a self-signed
	// TLS certificate generated in-memory on startup.
	server *http.Server

	// caCertPEM is the PEM-encoded CA certificate, made available inside the
	// container so the gh CLI trusts the proxy's TLS certificate.
	caCertPEM []byte

	// mu protects the done channel so Start and Shutdown can be called safely
	// from different goroutines.
	mu sync.Mutex

	// done is closed when the proxy server has fully shut down, allowing
	// callers to wait for clean termination.
	done chan struct{}
}

// New creates a new Proxy with the given options. The token from opts is used
// to set the Authorization header on forwarded requests, replacing whatever
// token the container-side gh CLI provides. Call Start to begin serving
// requests, and Shutdown to stop the proxy.
func New(opts Options) *Proxy {
	return &Proxy{
		opts: opts,
		done: make(chan struct{}),
	}
}

// Start generates a self-signed TLS certificate, binds to a random available
// port on the configured bind address, and starts the HTTPS proxy server. It
// returns the port number the proxy is listening on. The caller should call
// Shutdown to stop the proxy when the devcontainer session ends. The CA
// certificate PEM bytes are available via CACertPEM after Start returns.
func (p *Proxy) Start() (int, error) {
	// Generate a self-signed CA certificate and server certificate in-memory.
	// The CA cert is made available inside the container so the gh CLI trusts
	// the proxy's TLS certificate via NODE_EXTRA_CA_CERTS.
	expiry := p.opts.certExpiry()
	caCert, caKey, err := generateCA(expiry)
	if err != nil {
		return 0, fmt.Errorf("generating CA certificate: %w", err)
	}

	serverCert, serverKey, err := generateServerCert(caCert, caKey, ProxyHost, p.opts.GatewayIP, expiry)
	if err != nil {
		return 0, fmt.Errorf("generating server certificate: %w", err)
	}

	// Store the CA certificate PEM for mounting into the container.
	p.caCertPEM = pem.EncodeToMemory(&pem.Block{
		Type:  "CERTIFICATE",
		Bytes: caCert.Raw,
	})

	tlsCert := tls.Certificate{
		Certificate: [][]byte{serverCert.Raw},
		PrivateKey:  serverKey,
		Leaf:        serverCert,
	}

	// Bind to a random available port on the configured address. By default
	// this is the gateway IP (more secure — only reachable from the container's
	// network). Users can override via Options.BindAddr to e.g. "0.0.0.0" if
	// needed for their Docker network setup.
	bindAddr := p.opts.bindAddr()
	p.listener, err = net.Listen("tcp", bindAddr+":0")
	if err != nil {
		return 0, fmt.Errorf("binding proxy listener on %s: %w", bindAddr, err)
	}

	port := p.listener.Addr().(*net.TCPAddr).Port

	// Build the reverse proxy that forwards requests to the configured GitHub
	// API URL. The Director rewrites the request so it targets the real GitHub
	// API, and the transport enforces repository-level scoping.
	target, err := url.Parse(p.opts.apiURL())
	if err != nil {
		return 0, fmt.Errorf("parsing GitHub API URL %q: %w", p.opts.apiURL(), err)
	}
	reverseProxy := httputil.NewSingleHostReverseProxy(target)

	// Override the transport so we can intercept and check requests before
	// they are forwarded. The default transport would send requests directly
	// to the GitHub API; we need to enforce repository scoping and inject
	// the host token.
	reverseProxy.Transport = &scopingTransport{
		repository:   p.opts.Repository,
		token:        p.opts.Token,
		allowedPaths: p.opts.AllowedPaths,
	}

	reverseProxy.Director = p.director(target)
	reverseProxy.ErrorHandler = p.errorHandler

	p.server = &http.Server{
		Handler: reverseProxy,
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{tlsCert},
			MinVersion:   tls.VersionTLS12,
		},
	}

	// Start serving in a goroutine so Start can return immediately.
	go func() {
		defer close(p.done)
		// ServeTLS is used instead of Serve because the proxy must speak
		// HTTPS — the gh CLI requires HTTPS when connecting to a custom
		// GH_HOST. The TLS certificate and key are already loaded into
		// the server's TLSConfig, so the certFile and keyFile parameters
		// are empty strings.
		if err := p.server.ServeTLS(p.listener, "", ""); err != nil {
			if err != http.ErrServerClosed {
				slog.Error("proxy server error", "error", err)
			}
		}
	}()

	slog.Info("GitHub API proxy started",
		"port", port,
		"repository", p.opts.Repository,
		"bind_addr", bindAddr,
		"api_url", p.opts.apiURL())

	return port, nil
}

// Shutdown gracefully stops the proxy server. It waits for in-flight requests
// to complete (with a 5-second timeout) and then closes the listener. Call
// this when the devcontainer session ends to clean up the proxy.
func (p *Proxy) Shutdown() {
	p.mu.Lock()
	defer p.mu.Unlock()

	if p.server == nil {
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := p.server.Shutdown(ctx); err != nil {
		slog.Error("proxy shutdown error", "error", err)
	}

	// Wait for the serving goroutine to finish.
	<-p.done

	slog.Info("GitHub API proxy stopped")
}

// CACertPEM returns the PEM-encoded CA certificate. This is copied into
// the container at the configured CA cert path so the gh CLI trusts the
// proxy's self-signed TLS certificate via SSL_CERT_FILE and
// NODE_EXTRA_CA_CERTS.
func (p *Proxy) CACertPEM() []byte {
	return p.caCertPEM
}

// Opts returns a copy of the proxy's options. Used by callers that need
// access to the resolved configuration (e.g. CA cert paths for building
// remote env vars).
func (p *Proxy) Opts() Options {
	return p.opts
}

// WriteCACertToFile writes the PEM-encoded CA certificate to a temporary file
// on the host. The file is used as an intermediate step before copying the cert
// into the container so the gh CLI trusts the proxy's self-signed TLS
// certificate. Returns the path to the temp file. The caller should clean up
// the file when the proxy is shut down.
func WriteCACertToFile(caCertPEM []byte) (string, error) {
	tmp, err := os.CreateTemp("", "dcx-gh-proxy-ca-*.crt")
	if err != nil {
		return "", fmt.Errorf("creating temp file for CA cert: %w", err)
	}
	defer func() { _ = tmp.Close() }()

	if _, err := tmp.Write(caCertPEM); err != nil {
		_ = os.Remove(tmp.Name())
		return "", fmt.Errorf("writing CA cert: %w", err)
	}

	return tmp.Name(), nil
}

// BuildRemoteEnv constructs the environment variable flags that configure the
// gh CLI and git inside the container to route all GitHub API requests through
// the proxy. These are passed as --remote-env flags to devcontainer exec.
// Returns a slice of "--remote-env=NAME=VALUE" strings.
//
// The proxyPort is the port the proxy is listening on (returned by Start).
// The gateway IP is taken from the proxy's options.
//
// SSL_CERT_FILE points to a combined CA bundle (system certs + proxy CA) so
// that Go-based programs trust both the system CAs and the proxy's
// self-signed CA. This is necessary because Go's SSL_CERT_FILE replaces the
// system CA pool entirely rather than appending to it. NODE_EXTRA_CA_CERTS
// points to the proxy CA cert alone, since Node.js appends to the system
// trust store.
func (p *Proxy) BuildRemoteEnv(proxyPort int) []string {
	var envVars []string
	opts := p.opts

	// GH_HOST tells the gh CLI which GitHub host to target. The gh CLI
	// constructs the API URL as https://GH_HOST/api/v3/... so including
	// the port directs it to the proxy. Using the gateway IP (not
	// host.docker.internal) ensures connectivity in all environments.
	ghHost := fmt.Sprintf("%s:%d", opts.GatewayIP, proxyPort)
	envVars = append(envVars, fmt.Sprintf("--remote-env=GH_HOST=%s", ghHost))

	// SSL_CERT_FILE tells Go-based programs to trust the combined CA bundle
	// (system certs + proxy CA). Go's SSL_CERT_FILE replaces the system CA
	// pool entirely, so we must include the system CAs in the bundle to avoid
	// breaking HTTPS connectivity for other Go programs in the container.
	// NODE_EXTRA_CA_CERTS is also set for Node.js-based tools; unlike Go,
	// Node.js appends this cert to the system trust store.
	envVars = append(envVars, fmt.Sprintf("--remote-env=SSL_CERT_FILE=%s", opts.caBundlePath()))
	envVars = append(envVars, fmt.Sprintf("--remote-env=NODE_EXTRA_CA_CERTS=%s", opts.caCertPath()))

	// GIT_CONFIG_COUNT, GIT_CONFIG_KEY_0, and GIT_CONFIG_VALUE_0 configure
	// git to rewrite GitHub URLs so that git operations (clone, push, pull)
	// also route through the proxy. The insteadOf directive maps
	// https://GH_HOST/ URLs to https://github.com/ URLs so git can reach
	// the proxy when users clone/push to GitHub remotes.
	envVars = append(envVars, "--remote-env=GIT_CONFIG_COUNT=1")
	envVars = append(envVars, fmt.Sprintf("--remote-env=GIT_CONFIG_KEY_0=url.https://%s/.insteadOf", ghHost))
	envVars = append(envVars, "--remote-env=GIT_CONFIG_VALUE_0=https://github.com/")

	return envVars
}

// director returns a function that rewrites the incoming request so it targets
// the configured GitHub API URL instead of the proxy host. It replaces the
// request scheme, host, and URL path, and clears the Authorization header so
// the scoping transport can inject the host token. When the gh CLI connects to
// a custom GH_HOST (not github.com), it prefixes all API paths with
// "/api/v3/" (GitHub Enterprise convention). Since we forward to the
// configured API URL which does not use this prefix, we strip it here.
// This is used as the reverse proxy's Director function.
//
// The implementation was inspired by the gh-aw-mcpg proxy mode:
// https://github.com/github/gh-aw-mcpg/blob/main/docs/PROXY_MODE.md
func (p *Proxy) director(target *url.URL) func(*http.Request) {
	return func(req *http.Request) {
		req.URL.Scheme = target.Scheme
		req.URL.Host = target.Host
		req.Host = target.Host

		// Strip the "/api/v3/" prefix that the gh CLI adds when GH_HOST
		// is a custom host (GHE convention). The api.github.com endpoint
		// does not use this prefix — API paths are at the root (e.g.
		// /repos/owner/repo, not /api/v3/repos/owner/repo).
		req.URL.Path = strings.TrimPrefix(req.URL.Path, "/api/v3")

		// Also strip the "/api" prefix used by the gh CLI for GraphQL
		// requests. When GH_HOST is a custom host, the gh CLI sends
		// GraphQL requests to https://GH_HOST/api/graphql, but
		// api.github.com serves GraphQL at /graphql (without /api prefix).
		// This must come after the /api/v3 strip so that REST paths are
		// handled first.
		if strings.HasPrefix(req.URL.Path, "/api/") {
			req.URL.Path = strings.TrimPrefix(req.URL.Path, "/api")
		}

		if req.URL.Path == "" {
			req.URL.Path = "/"
		}

		// Clear the incoming Authorization header so the scoping transport
		// can inject the host token. The container-side gh CLI may send its
		// own (invalid) token — we always replace it with the real one.
		req.Header.Del("Authorization")

		// Remove the proxy-specific headers that the gh CLI may add when
		// connecting through a custom host. These are not needed by the
		// real GitHub API and could cause issues if forwarded.
		req.Header.Del("Proxy-Connection")
	}
}

// errorHandler logs proxy errors and returns a 502 Bad Gateway response to
// the client. This provides clearer error messages than the default reverse
// proxy error handler, which returns a generic "internal server error".
func (p *Proxy) errorHandler(w http.ResponseWriter, r *http.Request, err error) {
	slog.Error("proxy error", "path", r.URL.Path, "error", err)
	http.Error(w, fmt.Sprintf("proxy error: %v", err), http.StatusBadGateway)
}

// scopingTransport is an http.RoundTripper that enforces repository-level
// scoping on GitHub API requests. Before forwarding each request, it checks
// whether the request targets the allowed repository (or a non-repo path
// matching the allowed paths list). Requests failing both checks are rejected
// with 403 Forbidden. Allowed requests have the host's GitHub token injected
// as the Authorization header.
type scopingTransport struct {
	// repository is the allowed repository in "owner/repo" format. If empty,
	// no repository scoping is enforced and all requests are forwarded.
	repository string

	// token is the host's GitHub token, injected as the Authorization header
	// on forwarded requests. It replaces whatever the container-side gh CLI
	// sends (the director already cleared the incoming Authorization header).
	token string

	// allowedPaths is a list of non-repository API path prefixes that are
	// allowed through the proxy. If empty, all non-repo paths are allowed
	// (default behaviour). When non-empty, only paths starting with one of
	// the listed prefixes are allowed in addition to repo-scoped paths.
	allowedPaths []string
}

// RoundTrip implements http.RoundTripper. It checks the request path for
// repository scoping and allowed path prefixes, then either forwards the
// request to the GitHub API or rejects it with 403 Forbidden. The host token
// is always injected as the Authorization header on forwarded requests.
func (t *scopingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	// Enforce repository and path scoping.
	if err := t.checkScope(req.URL.Path); err != nil {
		return &http.Response{
			StatusCode: http.StatusForbidden,
			Header:     make(http.Header),
			Body:       ioBody(fmt.Sprintf("dcx-proxy: %s\n", err.Error())),
		}, nil
	}

	// Inject the host's GitHub token as the Authorization header. The director
	// already cleared any incoming Authorization header, so this is the only
	// token the forwarded request will carry.
	req.Header.Set("Authorization", "Bearer "+t.token)

	// Use the default transport to forward the request to the GitHub API.
	return http.DefaultTransport.RoundTrip(req)
}

// checkScope validates that the request path targets the allowed repository
// or an allowed non-repo path. GitHub API v3 paths for repository operations
// follow the pattern /repos/{owner}/{repo}/... . The function first checks
// if the path targets the allowed repository. If not, it checks whether the
// path matches an allowed non-repo prefix. If neither check passes, the
// request is rejected.
func (t *scopingTransport) checkScope(path string) error {
	repo, ok := extractRepo(path)
	if ok {
		// Path targets a specific repository — check if it matches the
		// allowed repository.
		if t.repository != "" && repo != t.repository {
			return fmt.Errorf("repository %q is not in the allowed scope (%q)", repo, t.repository)
		}
		return nil
	}

	// Path does not target a specific repository (e.g. /user, /app,
	// /graphql). Check it against the allowed paths list.
	if len(t.allowedPaths) > 0 {
		for _, prefix := range t.allowedPaths {
			if strings.HasPrefix(path, prefix) {
				return nil
			}
		}
		return fmt.Errorf("non-repo path %q is not in the allowed paths list", path)
	}

	// No allowed paths configured — allow all non-repo paths through.
	// These are needed for gh auth status and similar commands.
	return nil
}

// extractRepo parses a GitHub API v3 request path to extract the owner/repo
// segment. GitHub API paths for repository operations follow the pattern
// /repos/{owner}/{repo}/... . Returns the "owner/repo" string and true if
// found, or empty string and false if the path does not target a specific
// repository (e.g. /user, /app, /graphql).
func extractRepo(path string) (string, bool) {
	// Normalize: remove leading slash and split on slashes.
	segments := strings.Split(strings.TrimPrefix(path, "/"), "/")

	// GitHub API v3 repository paths start with "repos/{owner}/{repo}".
	if len(segments) < 3 || segments[0] != "repos" {
		return "", false
	}

	owner := segments[1]
	repo := segments[2]

	// The repo name may have additional segments after it (e.g.
	// /repos/owner/repo/issues), but we only need owner/repo.
	if owner == "" || repo == "" {
		return "", false
	}

	return owner + "/" + repo, true
}

// ioBody returns an io.ReadCloser that yields the given string. Used to
// construct response bodies for rejected requests without allocating a
// bytes.Buffer or pipe.
func ioBody(s string) io.ReadCloser {
	return io.NopCloser(strings.NewReader(s))
}

// generateCA creates a self-signed CA certificate and ECDSA private key. The
// certificate is valid for the given expiry duration (ephemeral — only for the
// duration of the proxy session). The key uses P-256 curve which is widely
// supported and provides adequate security for short-lived certificates.
// Returns the parsed certificate and private key. Called once on proxy startup.
func generateCA(expiry time.Duration) (*x509.Certificate, *ecdsa.PrivateKey, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generating CA key: %w", err)
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, fmt.Errorf("generating CA serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"dcx proxy CA"},
			CommonName:   "dcx proxy CA",
		},
		NotBefore:             time.Now(),
		NotAfter:              time.Now().Add(expiry),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, nil, fmt.Errorf("creating CA certificate: %w", err)
	}

	cert, err := x509.ParseCertificate(certDER)
	if err != nil {
		return nil, nil, fmt.Errorf("parsing CA certificate: %w", err)
	}

	return cert, key, nil
}

// generateServerCert creates a TLS server certificate signed by the given CA
// certificate and key. The certificate is valid for the given expiry duration
// and includes the given host as a DNS SAN (Subject Alternative Name) and the
// gatewayIP as an IP SAN. The IP SAN is needed because the gh CLI connects to
// the proxy via the Docker bridge gateway IP, and TLS verification checks the
// SAN against the connection target. The key uses P-256 curve.
// Returns the parsed certificate and private key. Called once on proxy startup
// after generateCA.
func generateServerCert(caCert *x509.Certificate, caKey *ecdsa.PrivateKey, host, gatewayIP string, expiry time.Duration) (*x509.Certificate, *ecdsa.PrivateKey, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generating server key: %w", err)
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, fmt.Errorf("generating server serial number: %w", err)
	}

	// Build the SAN lists. The DNS name is the hostname (host.docker.internal)
	// and the IP address is the Docker bridge gateway. Both are needed so the
	// gh CLI can verify the TLS connection regardless of which address it
	// uses to reach the proxy.
	dnsNames := []string{host}
	var ipAddrs []net.IP
	if gatewayIP != "" {
		ip := net.ParseIP(gatewayIP)
		if ip != nil {
			ipAddrs = append(ipAddrs, ip)
		}
	}

	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"dcx proxy"},
			CommonName:   host,
		},
		NotBefore:   time.Now(),
		NotAfter:    time.Now().Add(expiry),
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:    dnsNames,
		IPAddresses: ipAddrs,
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, caCert, &key.PublicKey, caKey)
	if err != nil {
		return nil, nil, fmt.Errorf("creating server certificate: %w", err)
	}

	cert, err := x509.ParseCertificate(certDER)
	if err != nil {
		return nil, nil, fmt.Errorf("parsing server certificate: %w", err)
	}

	return cert, key, nil
}
